global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "airflow"
    static_configs:
      - targets: ["airflow:8080"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9092"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "cassandra"
    static_configs:
      - targets: ["cassandra-exporter:7070"]
  
  - job_name: "mongo"
    static_configs:
      - targets: ["mongo-exporter:9216"]